### ISSUE TITLE
Textual descriptions CelebA

### ISSUE THREAD

**Issue by davidstap** [2KangHo/AttnGAN-CelebA#1]
Hi, I was wondering how you created the textual descriptions for the CelebA dataset? I know that the dataset consists of images with 40 binary attributes, but to the best of my knowledge there are not official textual descriptions.

Thanks, David

**Comment by 2KangHo** [comment]
I made textual descriptions using the 40 binary attributes with my text-auto-generating code. If 'Wavy Hair' is 1 and 'woman' is 1, the code generate text: 'The woman has wavy hair' and 'A woman's hair is wavy' etc. And article (e.g. 'A', 'The') is generated randomly.
Thx.
